version: '3.1'

services:
  springboot:
    image: pravalika52/spring-app:1
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=pravali
    - MONGO_DB_PASSWORD=pravali
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
    - springappnetwork  
    
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=pravali
    - MONGO_INITDB_ROOT_PASSWORD=pravali
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true
